version: '3.8'
services:
    mysql:
        image: 'mysql:8.0'
        command: mysqld --default-authentication-plugin=mysql_native_password
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
            - MYSQL_PASSWORD=${DB_PASSWORD}
        ports:
            - 3306:3306
        volumes:
            - 'mysql_data:/var/lib/mysql'
        restart: always

    app:
        build:
            context: ./
            dockerfile: ./docker/app/Dockerfile
        depends_on:
            - mysql
        environment:
            - APP_KEY=base64:Szb/GcJVd+s76cbA+BDdEoPksSXaRmU4uyxINiE02Oc=
            - DB_HOST=${DB_HOST}
            - DB_PORT=${DB_PORT}
            - DB_DATABASE=${DB_DATABASE}
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}
        volumes:
            - ./:/var/www/html
        restart: always

    nginx:
        build:
            context: ./docker/nginx
        volumes:
            - ./:/var/www/html
        depends_on:
            - app
        ports:
            - 80:80
        environment:
            - FASTCGI_HOST=app
            - FASTCGI_PORT=9000
        restart: always


volumes:
    mysql_data:
        driver: local
